name: Automated Checks

on:
  push:
    branches: [develop, master, release**]

jobs:
  phpmnd:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1']

    name: Magic Numbers @ PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@v3.0.10
        with:
          php-version: ${{ matrix.php }}

      - name: Cache Composer Dependencies
        uses: actions/cache@v2
        id: cache-composer
        with:
          path: vendor
          key: cache-composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}

      - name: Install Dependencies
        env:
          ENLIGHTN_USERNAME: ${{ secrets.ENLIGHTN_USERNAME }}
          ENLIGHTN_API_TOKEN: ${{ secrets.ENLIGHTN_API_TOKEN }}
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: |
          composer config http-basic.satis.laravel-enlightn.com "$ENLIGHTN_USERNAME" "$ENLIGHTN_API_TOKEN"
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: phpmnd
        id: phpmnd-run
        run: ./vendor/bin/phpmnd \
          --exclude-path=storage \
          --exclude=tests \
          --ignore-funcs=for \
          --progress .
